mysql:
  image: openzipkin/zipkin-mysql:1.33.2
  ports:
    - 3306:3306

query:
  image: openzipkin/zipkin-java:0.5.3
  environment:
    # Remove TRANSPORT_TYPE to disable tracing
    - TRANSPORT_TYPE=http
    - STORAGE_TYPE=mysql
  ports:
    - 9411:9411
    - 9901:9901
  links:
    - mysql:storage

web:
  image: openzipkin/zipkin-web:1.33.2
  environment:
    # Remove TRANSPORT_TYPE to disable tracing
    - TRANSPORT_TYPE=http
  ports:
    - 8080:8080
    - 9990:9990
  links:
    - query

rabbitmq:
  image: rabbitmq:management
  ports:
    - 9672:5672
    - 15672

