mysql:
  image: openzipkin/zipkin-mysql:1.38.0
  ports:
    - 3306:3306

query:
  image: openzipkin/zipkin-java:0.9.1
  environment:
    # Remove TRANSPORT_TYPE to disable tracing
    - TRANSPORT_TYPE=http
    - STORAGE_TYPE=mysql
  ports:
    - 9411:9411
    - 8080:9411
  links:
    - mysql:storage

rabbitmq:
  image: rabbitmq:management
  ports:
    - 9672:5672
    - 15672

