server.port: 8083
spring:
  application:
    name: service3
  sleuth:
    sampler:
      probability: 1.0
    # you have to explicitly provide baggage keys
    baggage-keys:
      - baggage
      - key

logging.level.org.springframework.cloud.sleuth: DEBUG

management.endpoints.web.base-path: /
management.endpoints.web.exposure.include: "*"